name: cesarsotovalero.net
url: "https://www.cesarsotovalero.net"
title: "César Soto Valero"
description: "César - Computer Scientist"
keywords: "software engineering,research,java,developer,machine learning,software technology,phd student"
logo: https://www.cesarsotovalero.net/img/pages/cesar/avatar-icon-2024.jpg

navbar-links:
  Blog: "blog"
  LinkedIn: "linkedin"
  YouTube: "youtube"
  Podcasts: "podcasts"
  Talks: "talks"
  About: "about-me"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/pages/cesar/avatar-icon-2024.jpg"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
# title-img: /path/to/image

# --- Background colour/image options --- #

# By default, the navigation bar and footer have a light gray background, and the main page
# has a white background. You can specify a different background colour or a background image
# for the navigation bar, the main page, and the footer.
# navbar-col: "blue"
# navbar-img: "/img/bgimage.png"
# footer-col: "blue"
# footer-img: "/img/bgimage.png"
# page-col: "#FF0000"
# page-img: "/img/bgimage.png"

navbar-img: "/img/pages/all/bg.png"
# footer-col: "blue"
footer-img: "/img/pages/all/bg.png"
# page-col: "#FF0000"
page-img: "/img/pages/all/noise.png"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: César Soto Valero
  github: cesarsotovalero
  twitter: cesarsotovalero
  linkedin: cesarsotovalero
  stackoverflow: 10480869/cesarsotovalero?tab=profile
  youtube: channel/UCR4rI98w6-MqYoCS6jR9LGg
  email: NaN
  reddit: NaN
  snapchat: NaN
  instagram: NaN
  spotify: NaN
  telephone: NaN

twitter:
  username: cesarsotovalero
  card: summary

# Select which links to show in the footer
footer-links-active:
  rss: true
  facebook: false
  email: false
  twitter: true
  google-plus: false
  github: true
  reddit: false
  linkedin: true
  xing: false
  stackoverflow: true
  snapchat: false
  instagram: false
  youtube: true
  spotify: false
  telephone: false
  steam: false
  twitch: false
  yelp: false

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  google: true
  linkedin: true

social:
  name: César Soto Valero
  links:
    - https://twitter.com/cesarsotovalero
    - https://www.facebook.com/cesar.sotovalero.9/
    - https://se.linkedin.com/in/cesarsotovalero
    - https://github.com/cesarsotovalero

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer

# --- Misc --- #

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-107061705-1"

# Google Tag Manager ID
#gtm: ""

# Facebook App ID
# fb_app_id: ""

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: ""

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
encoding: utf-8
timezone: "America/Vancouver"
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
highlighter: rouge
syntax_highlighter_opts:
  block:
    line_numbers: true
permalink: /blog/:title.html
#paginate: 20
#paginate_path: "/blog/page:num/"
excerpt_separator: <!--more-->

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
      carbonads: true
      before-content: [carbonads.html]
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true
      carbonads: true
      before-content: [carbonads.html]

# Use tags pages (not recommended if you are deploying via GitHub pages, only set to true if deploying locally with ruby)
link-tags: false


# This files will be included in the gh-pages
include:
  - _pages
  - .well-known
  - yandex_640034aaee9b8f83.html
  - google974bdea481135366.html

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile
  - Rakefile
  - httpd.conf
  - id_rsa.enc
  - s3cfg.enc
  - uml
  - node_modules
  - run_jekyll.sh
  - tag_generator.py
  - .ruby-version
  - vendor
  - feed.xml

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "Add a thumbnail image to your post."
          placeholder: "Thumbnail"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

gem:
  - jekyll-paginate
  - jemoji
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-plantuml # https://plantuml.com
  - jekyll-redirect-from
  - jekyll-bits
  - jekyll-feed
  - jekyll-tagging
  - jekyll-responsive-image
  - jekyll-seo-tag
  - jekyll-mermaid

plugins:
  - jekyll-feed
  - jemoji
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-responsive-image
  - jekyll-seo-tag
  - jekyll-last-modified-at
  - jekyll-toc

toc:
  ordered_list: true
  min_level: 1 # default: 1
  max_level: 1 # default: 6

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
  date-format: '%d-%b-%y'

# jekyll-feed
feed:
  title: cesarsotovalero.net
  subtitle: César Soto Valero

sass:
  style: compressed
  deploy_style: compressed

# jekyll-responsive-image @see https://github.com/wildlyinaccurate/jekyll-responsive-image#templates
responsive_image:
  template: _includes/picture-responsive.html
  default_quality: 80
  sizes:
    - width: 640
    - width: 768
    - width: 1024
    - width: 1366
    - width: 1600
    - width: 1920
  strip: true

# To check for broken external links, run the following in the CLI:
# gem install html-proofer
# htmlproofer ./_site --only-4xx --check-external-hash --url-ignore '/^\/(?!\/)/'