source 'https://rubygems.org'

# Jekyll gems
gem 'jekyll', '4.3.2'
gem 'jekyll-paginate'
gem 'jekyll-sitemap'
gem 'jekyll-tagging', git: 'https://github.com/pattex/jekyll-tagging', branch: 'master'
gem 'jekyll-bits'
gem 'jekyll-plantuml'
gem 'jekyll-responsive-image'
gem 'jekyll-seo-tag'
gem 'jekyll-toc'
gem 'jekyll-mermaid'
gem "jekyll-feed"
gem 'jekyll-gist'

# Non-jekyll gems
gem 'jemoji'
gem 'webrick'
gem 'fastimage'
gem 'rmagick'
gem 'jslint'
gem 'html-proofer'
gem 'kramdown'
gem 'liquid'
gem 'mail'
gem 'nokogiri'
gem 'nuggets'
gem 'pygments.rb'
gem 'rainbow'
gem 'rake'
gem 'redcarpet'
gem 'rubocop'
gem 'rubocop-rspec'
gem 'sass'
gem 'scss_lint'
gem 'trollop'
gem 'uuidtools'
gem 'w3c_validators'
gem "sprockets", "~> 3.7"
gem 'json'
gem 'jekyll-last-modified-at'