name: Deploy
permissions:
  pages: write
  id-token: write

on:
  push:
    branches:
      - master

env:
  RUBY_VERSION: 3.2.2

jobs:
  deploy:
    name: gh-pages
    runs-on: ubuntu-22.04

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Install dependencies
        run: bundle install

      - name: Building site
        run: JEKYLL_ENV=production bundle exec jekyll build --profile ben--trace
        env:
          GISCUS_DATA_REPO_ID: ${{ secrets.GISCUS_DATA_REPO_ID }}
          GISCUS_GISCUS_DATA_CATEGORY_ID: ${{ secrets.GISCUS_DATA_REPO_ID }}
          YOUTUBE_API_TOKEN: ${{ secrets.YOUTUBE_API_TOKEN }}
          GMAIL: ${{ secrets.CESAR_PERSONAL_GMAIL }}

      - name: Install Minify deb package on Ubuntu
        run: sudo apt-get update && sudo apt-get install --no-install-recommends --yes minify

      # https://github.com/tdewolff/homebrew-tap/
      #      - name: Install Minify using Homebrew
      #        run: brew install tdewolff/tap/minify

      # https://github.com/tdewolff/minify/tree/master/cmd/minify#usage
      - name: Minify HTML files
        run: |
          minify --type=html --recursive --output "./" --match=\.html "./_site/" \
          --html-keep-conditional-comments \
          --html-keep-default-attrvals \
          --html-keep-document-tags \
          --html-keep-end-tags \
          --verbose

      - name: Minify JSON files
        run: |
          minify --type=json --recursive --output "./" --match=\.json "./_site/" --verbose || true

      - name: Minify JavaScript files
        run: |
          minify --mime=application/javascript --recursive --output "./" --match=\.js "./_site/js" --verbose || true

      - name: Minify CSS files
        run: |
          minify --type=css --recursive --output "./" --match=\.css "./_site/css" --verbose || true

      # Upload built site for GitHub Pages
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      # Deploy to GitHub Pages environment
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
