name: Deploy

on:
  push:
    branches:
      - master

permissions:
  pages: write        # allow deploy-pages to publish
  id-token: write     # allow OIDC for Pages deploy

env:
  RUBY_VERSION: 3.2.2

jobs:
  build:
    name: Build & Upload
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: false    # caching handled by the Jekyll action

      - name: Build Jekyll site (with all plugins)
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true      # caches vendor/bundle for speed
          prettier: false         # skip extra formatting
        env:
          GISCUS_DATA_REPO_ID:            ${{ secrets.GISCUS_DATA_REPO_ID }}
          GISCUS_GISCUS_DATA_CATEGORY_ID: ${{ secrets.GISCUS_DATA_REPO_ID }}
          YOUTUBE_API_TOKEN:              ${{ secrets.YOUTUBE_API_TOKEN }}
          GMAIL:                          ${{ secrets.CESAR_PERSONAL_GMAIL }}

      - name: Install Minify
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends --yes minify

      - name: Minify HTML files
        run: |
          minify \
            --type=html \
            --recursive \
            --output="./" \
            --match '\.html' "./_site/" \
            --html-keep-conditional-comments \
            --html-keep-default-attrvals \
            --html-keep-document-tags \
            --html-keep-end-tags \
            --verbose

      - name: Minify JSON files
        run: |
          minify --type=json --recursive --output="./" --match '\.json' "./_site/" --verbose || true

      - name: Minify JavaScript files
        run: |
          minify --mime=application/javascript --recursive --output="./" --match '\.js' "./_site/js" --verbose || true

      - name: Minify CSS files
        run: |
          minify --type=css --recursive --output="./" --match '\.css' "./_site/css" --verbose || true

      - name: Create CNAME file
        run: echo 'www.cesarsotovalero.net' > _site/CNAME

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site/

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-22.04
    environment:
      name: github-pages
      url: https://www.cesarsotovalero.net

    steps:
      - name: Deploy artifact to GitHub Pages
        uses: actions/deploy-pages@v4
