name: Update University Ranking

on:
  schedule:
    # Runs at 00:00 UTC on the 1st of every month
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: write # needed for pushing changes

jobs:
  update-ranking:
    runs-on: ubuntu-latest
    concurrency:
      group: update-ranking
      cancel-in-progress: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # defaults to GITHUB_TOKEN; good for push
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests beautifulsoup4 pyyaml

      - name: Run update script
        run: python scripts/update_kth_ranking.py

      - name: Commit and push if changed
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add _data/university_ranking.yml
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Update ranking of KTH university"
          # Rebase in case default branch moved
          git pull --rebase
          git push
