name: Update LinkedIn Posts

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-linkedin-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          # Check out the repository into the _data folder
          path: _data
          # Enable sparse checkout to fetch only specific files
          sparse-checkout: true
          # Define the files or directories to include
          sparse-checkout-config: |
            _data/linkedin-posts.json

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch LinkedIn posts
        working-directory: _data
        env:
          RAPIDAPI_LINKEDIN_DATA_API_KEY: ${{ secrets.RAPIDAPI_LINKEDIN_DATA_API_KEY }}
        run: |
          # Generate URL-encoded date string for last week's UTC date at 00:00
          encodedDate=$(date -u -d '7 days ago' +'%Y-%m-%d 00:00' | sed 's/ /%20/g;s/:/%3A/g')
          echo "Fetching posts from date: $encodedDate"
          # Fetch LinkedIn posts using the API; save to a temp file in _data.
          curl --request GET \
            --url "https://linkedin-data-api.p.rapidapi.com/get-profile-posts?username=cesarsotovalero&postedAt=${encodedDate}" \
            --header "x-rapidapi-host: linkedin-data-api.p.rapidapi.com" \
            --header "x-rapidapi-key: $RAPIDAPI_LINKEDIN_DATA_API_KEY" \
            -o linkedin-posts-new.json

      - name: Merge new posts with existing JSON
        working-directory: _data
        run: |
          # If an existing JSON file is present, merge new data with it.
          if [ -f linkedin-posts.json ]; then
            originalCount=$(jq '.data | length' linkedin-posts.json)
            jq -s '{
              success: true,
              message: "",
              data: (.[0].data + .[1].data | sort_by(.postedDateTimestamp) | reverse)
            }' linkedin-posts-new.json linkedin-posts.json > merged.json
            newCount=$(jq '.data | length' merged.json)
            echo "Number of new entries added: $((newCount - originalCount))"
          else
            jq '.data |= sort_by(.postedDateTimestamp) | .data |= reverse' linkedin-posts-new.json > merged.json
            newCount=$(jq '.data | length' merged.json)
            echo "Number of new entries added: $newCount"
          fi
          # Replace the old file with the merged file.
          mv merged.json linkedin-posts.json
          # Clean up the temporary file.
          rm linkedin-posts-new.json

      - name: Commit and push changes if any
        working-directory: _data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add linkedin-posts.json
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update LinkedIn posts $(date -u +'%Y-%m-%d')"
            git push
          else
            echo "No changes to commit"
          fi