name: Update LinkedIn Posts and Download Images
on:
  schedule:
    - cron: "0 0 * * 1" # Runs every Monday at midnight UTC
  workflow_dispatch:

jobs:
  update-linkedin-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch LinkedIn posts
        env:
          RAPIDAPI_LINKEDIN_DATA_API_KEY: ${{ secrets.RAPIDAPI_LINKEDIN_DATA_API_KEY }}
        run: |
          # Generate URL-encoded date string for last week's UTC date at 00:00
          encodedDate=$(date -u -d '7 days ago' +'%Y-%m-%d 00:00' | sed 's/ /%20/g;s/:/%3A/g')
          echo "Fetching posts from date: $encodedDate"
          # Fetch LinkedIn posts using the API
          curl --request GET \
            --url 'https://linkedin-scraper-api-real-time-fast-affordable.p.rapidapi.com/profile/posts?username=cesarsotovalero' \
            --header 'x-rapidapi-host: linkedin-scraper-api-real-time-fast-affordable.p.rapidapi.com' \
            --header "x-rapidapi-key: $RAPIDAPI_LINKEDIN_DATA_API_KEY" \
            -o linkedin-posts.json

      - name: Merge new posts with existing JSON
        run: |
          # If the JSON file already exists, merge new data with the existing entries.
          if [ -f _data/linkedin-posts.json ]; then
            # count existing posts
            originalCount=$(jq '.data.posts | length' _data/linkedin-posts.json)
            # merge posts arrays using posted_at.timestamp
            jq -s '{
              success: true,
              message: "",
              data: {
                posts: (.[0].data.posts + .[1].data.posts | unique_by(.posted_at.timestamp) | sort_by(.posted_at.timestamp) | reverse)
              }
            }' linkedin-posts.json _data/linkedin-posts.json > merged.json
            newCount=$(jq '.data.posts | length' merged.json)
            echo "Number of new entries added: $((newCount - originalCount))"
          else
            # initialize new feed sorted by timestamp
            jq '{
              success: true,
              message: "",
              data: {
                posts: (.data.posts | sort_by(.posted_at.timestamp) | reverse)
              }
            }' linkedin-posts.json > merged.json
            newCount=$(jq '.data.posts | length' merged.json)
            echo "Number of new entries added: $newCount"
          fi
          # Move the merged file to the _data directory, overwriting if it exists
          mv -f merged.json _data/linkedin-posts.json

      - name: Remove temporary posts file
        run: rm -f linkedin-posts.json

      - name: Create assets directory if it doesn't exist
        run: mkdir -p assets/images/linkedin

      - name: Download images from new entries
        shell: bash
        run: |
          # First, validate the JSON structure
          if ! jq -e . >/dev/null 2>&1 < _data/linkedin-posts.json; then
            echo "Error: Invalid JSON in _data/linkedin-posts.json"
            exit 1
          fi
          # Collect posts with media into an array to avoid broken pipes
          mapfile -t posts < <(
            jq -r '.data.posts[] | select(.media != null and (.media | length > 0)) | @base64' _data/linkedin-posts.json
          )
          for post_b64 in "${posts[@]}"; do
            [ -z "$post_b64" ] && continue
            post=$(echo "$post_b64" | base64 --decode)
            posted_ts=$(echo "$post" | jq -r '.posted_at.timestamp // empty')
            [ -z "$posted_ts" ] && { echo "Warning: Missing timestamp for post, skipping"; continue; }
            dir="assets/images/linkedin/${posted_ts}"
            mkdir -p "$dir"
            # Collect images into array
            mapfile -t images < <(
              echo "$post" | jq -r '.media[] | select(.url != null) | @base64'
            )
            for img_b64 in "${images[@]}"; do
              [ -z "$img_b64" ] && continue
              img=$(echo "$img_b64" | base64 --decode)
              url=$(echo "$img" | jq -r '.url // empty')
              width=$(echo "$img" | jq -r '.width // empty')
              height=$(echo "$img" | jq -r '.height // empty')
              if [ -z "$url" ] || [ -z "$width" ] || [ -z "$height" ]; then
                echo "Warning: Missing image properties, skipping"
                continue
              fi
              filename="${width}x${height}.jpg"
              output_path="${dir}/${filename}"
              if [ ! -f "$output_path" ]; then
                echo "Downloading image to $output_path"
                if ! curl -L "$url" -o "$output_path"; then
                  echo "Failed to download $url, skipping"
                fi
              else
                echo "Image $output_path already exists, skipping"
              fi
            done
          done

      - name: Commit and push changes if any
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add _data/linkedin-posts.json
          git add assets/images/linkedin/
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update LinkedIn posts and images $(date -u +'%Y-%m-%d')"
            git push
          else
            echo "No changes to commit"
          fi
