name: Deploy

on:
  push:
    branches:
      - master

env:
  RUBY_VERSION: 3.0.1

jobs:
  deploy:
    name: gh-pages
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Building site
        run: JEKYLL_ENV=production bundle exec jekyll build --profile --trace
        env:
          GISCUS_DATA_REPO_ID: ${{ secrets.GISCUS_DATA_REPO_ID }}
          GISCUS_GISCUS_DATA_CATEGORY_ID: ${{ secrets.GISCUS_DATA_REPO_ID }}

      - name: Install Minify deb package on Ubuntu
        run: apt-get update && apt-get install --no-install-recommends --yes minify

      # https://github.com/tdewolff/homebrew-tap/
#      - name: Install Minify using Homebrew
#        run: brew install tdewolff/tap/minify

      # https://github.com/tdewolff/minify/tree/master/cmd/minify#usage
      - name: Minify HTML files
        run: |
          minify --type=html --recursive --output "./" --match=\.html "./_site/" \
          --html-keep-conditional-comments \
          --html-keep-default-attrvals \
          --html-keep-document-tags \
          --html-keep-end-tags \
          --html-keep-quotes \
          --verbose

      - name: Minify JSON files
        run: |
          minify --type=json --recursive --output "./" --match=\.json "./_site/" --verbose || true

      - name: Minify JavaScript files
        run: |
          minify --mime=application/javascript --recursive --output "./" --match=\.js "./_site/js" --verbose || true

      - name: Minify CSS files
        run: |
          minify --type=css --recursive --output "./" --match=\.css "./_site/css" --verbose || true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: success()
        with:
          allow_empty_commit: false
          cname: www.cesarsotovalero.net
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./_site/
